stages:
  - lint
  - test

default:
  image: python:3.11
  variables:
    FLASK_ENV: testing
    PYTHONDONTWRITEBYTECODE: "1"
    PIP_DISABLE_PIP_VERSION_CHECK: "1"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/pip
  before_script:
    # Enter project folder if files live under 'cue419/'
    - |
      if [ -f requirements.txt ]; then
        echo "Using repo root"
      elif [ -f cue419/requirements.txt ]; then
        cd cue419
        echo "Switched into cue419/"
      else
        echo "requirements.txt not found in root or cue419/"
        ls -la
        exit 1
      fi
    - python -V
    - pip install --upgrade pip
    - pip config set global.cache-dir .cache/pip
    - pip install -r requirements.txt
    - pip install pytest

lint:
  stage: lint
  script:
    - pip install ruff black
    - ruff --format=github .
    - black --check .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

test:
  stage: test
  script:
    - mkdir -p data   # ensure sqlite folder exists if your app writes here
    - pytest -q --junitxml=junit.xml
  artifacts:
    when: always
    reports:
      junit: junit.xml
    paths:
      - junit.xml
      - .pytest_cache/
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH
